# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4
        environment:
          FUCKER_EXECUTOR_DATABASE_HOST: 127.0.0.1
          FUCKER_EXECUTOR_DATABASE_PASSWORD: root
      - image: circleci/mariadb
        environment:
          MYSQL_ROOT_PASSWORD: root

    working_directory: ~/executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-dependencies-{{ checksum "test-requirements.txt" }}
            - v1-test-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install -r test-requirements.txt
            pipenv install -r requirements.txt
      - save_cache:
          key: v1-test-dependencies-{{ checksum "test-requirements.txt" }}
          paths:
            - ./venv
      - run:
          name: run pylint
          command: |
            pipenv run pylint executor
      - run:
          name: run unittest
          command: |
            pipenv run stestr run
      - run:
          name: report coverage
          command: |
            export COVERALLS_REPO_TOKEN=Phto4xcJLYiucsZeWP1JBqluKgJYj6YJn
            pipenv run coverage run --source=executor/ setup.py test
            pipenv run coveralls
